services:
  ade-seleniarm:
    image: seleniarm/standalone-firefox:latest
    environment:
      - SE_NODE_MAX_SESSIONS=99
      - SE_NODE_SESSION_TIMEOUT=63072000 # 2 years
      - VNC_NO_PASSWORD=1
      - SE_OPTS=--enable-managed-downloads true
    shm_size: 2gb

  ade-mongodb:
    image: mongo:latest
    volumes:
      - ./docker_volumes/mongodb/db:/data/db
      - ./docker_volumes/mongodb/configdb:/data/configdb

  ade-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=ade
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql

  ade-python-parser:
    build: ade_parser/.
    depends_on:
      - ade-mongodb
      - ade-seleniarm
      - ade-mysql
    env_file:
      - stack.env
    volumes:
      - ./docker_volumes/screenshots:/screenshots

  ade-public-api:
    build: api/.
    depends_on:
      - ade-mongodb
      - ade-mysql
    env_file:
      - stack.env