[project]
name = "ade_api"
version = "0.0.1"
description = "API for ADE Planning"

dependencies = [
    'chromedriver_autoinstaller==0.6.2',
    'Flask==2.3.3',
    'selenium==4.12.0',
    'selenium_stealth==1.0.6'
]

[tool.setuptools]
py-modules = []